// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/Lexer.flex

import java_cup.runtime.*;
import java.io.*;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\1\4\1\5\1\6\1\7\1\10\1\0\1\11\2\0"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\11\21"+
    "\1\22\1\0\1\23\1\0\1\24\1\0\1\25\4\26"+
    "\1\27\25\26\3\0\1\30\1\31\1\0\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\26"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\26\1\56\1\26\1\57\1\26"+
    "\1\60\1\61\1\62\1\63\42\0\1\64\u015e\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\2\1\1\16\1\17\1\20\16\17\2\1\1\21\1\1"+
    "\1\0\1\22\1\0\1\23\1\24\3\0\1\25\1\26"+
    "\1\27\1\30\1\31\10\17\1\32\6\17\1\33\10\17"+
    "\1\0\1\34\1\35\1\2\1\36\1\37\1\40\1\41"+
    "\5\17\1\42\10\17\1\43\7\17\1\0\1\17\1\44"+
    "\1\17\1\45\1\46\1\47\1\17\1\50\12\17\1\51"+
    "\2\17\1\52\1\17\1\53\1\54\1\55\1\56\6\17"+
    "\1\57\4\17\1\60\1\17\1\61\1\62\1\63\1\17"+
    "\1\64\2\17\1\65\1\66\1\67\2\17\1\70\1\17"+
    "\1\71\1\72\1\73";

  private static int [] zzUnpackAction() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\65\0\152\0\65\0\237\0\65\0\65"+
    "\0\65\0\324\0\65\0\u0109\0\65\0\u013e\0\65\0\u0173"+
    "\0\u01a8\0\u01dd\0\u0212\0\65\0\u0247\0\65\0\u027c\0\u02b1"+
    "\0\u02e6\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\u0459"+
    "\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597\0\65\0\u05cc"+
    "\0\237\0\65\0\u0601\0\65\0\65\0\u0636\0\u066b\0\u06a0"+
    "\0\65\0\65\0\65\0\65\0\65\0\u06d5\0\u070a\0\u073f"+
    "\0\u0774\0\u07a9\0\u07de\0\u0813\0\u0848\0\u0247\0\u087d\0\u08b2"+
    "\0\u08e7\0\u091c\0\u0951\0\u0986\0\u0247\0\u09bb\0\u09f0\0\u0a25"+
    "\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9\0\u0b2e\0\u0b63\0\65\0\65"+
    "\0\u0b98\0\65\0\u0636\0\u066b\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c"+
    "\0\u0ca1\0\u0cd6\0\u0247\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf"+
    "\0\u0e14\0\u0e49\0\u0e7e\0\u0247\0\u0eb3\0\u0ee8\0\u0f1d\0\u0f52"+
    "\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u105b\0\u0247\0\u1090\0\u0247"+
    "\0\u0247\0\u0247\0\u10c5\0\u0247\0\u10fa\0\u112f\0\u1164\0\u1199"+
    "\0\u11ce\0\u1203\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u0247\0\u130c"+
    "\0\u1341\0\u0247\0\u1376\0\u0247\0\u0247\0\u0247\0\u0247\0\u13ab"+
    "\0\u13e0\0\u1415\0\u144a\0\u147f\0\u14b4\0\u0247\0\u14e9\0\u151e"+
    "\0\u1553\0\u1588\0\u15bd\0\u15f2\0\u0247\0\u0247\0\u0247\0\u1627"+
    "\0\u0247\0\u165c\0\u1691\0\u0247\0\u0247\0\u0247\0\u16c6\0\u16fb"+
    "\0\u1730\0\u1765\0\u0247\0\u179a\0\u0247";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\2\1\17\2\20"+
    "\1\21\1\22\1\23\1\24\2\25\1\26\1\27\1\25"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\25\1\36"+
    "\1\25\1\37\1\25\1\40\3\25\1\41\1\42\1\43"+
    "\1\25\1\44\1\25\1\45\1\46\1\2\1\47\1\50"+
    "\67\0\1\3\62\0\5\51\1\52\57\51\20\0\2\53"+
    "\4\0\2\53\1\0\27\53\20\0\1\54\66\0\1\55"+
    "\65\0\1\56\1\57\2\20\5\0\1\60\6\0\1\60"+
    "\107\0\1\61\20\0\1\62\5\0\1\63\35\0\1\64"+
    "\27\0\1\65\60\0\2\25\4\0\2\25\1\0\27\25"+
    "\25\0\2\25\4\0\2\25\1\0\1\66\26\25\25\0"+
    "\2\25\4\0\2\25\1\0\16\25\1\67\2\25\1\70"+
    "\5\25\25\0\2\25\4\0\2\25\1\0\1\25\1\71"+
    "\6\25\1\72\1\73\4\25\1\74\10\25\25\0\2\25"+
    "\4\0\2\25\1\0\5\25\1\75\10\25\1\76\10\25"+
    "\25\0\2\25\4\0\2\25\1\0\13\25\1\77\1\100"+
    "\3\25\1\101\6\25\25\0\2\25\4\0\2\25\1\0"+
    "\1\25\1\102\11\25\1\103\13\25\25\0\2\25\4\0"+
    "\2\25\1\0\21\25\1\104\5\25\25\0\2\25\4\0"+
    "\2\25\1\0\6\25\1\105\6\25\1\106\11\25\25\0"+
    "\2\25\4\0\2\25\1\0\5\25\1\107\21\25\25\0"+
    "\2\25\4\0\2\25\1\0\1\110\26\25\25\0\2\25"+
    "\4\0\2\25\1\0\5\25\1\111\21\25\25\0\2\25"+
    "\4\0\2\25\1\0\23\25\1\112\1\25\1\113\1\25"+
    "\25\0\2\25\4\0\2\25\1\0\21\25\1\114\5\25"+
    "\25\0\2\25\4\0\2\25\1\0\10\25\1\115\16\25"+
    "\22\0\1\116\71\0\1\117\1\0\1\120\124\0\1\121"+
    "\11\0\1\122\73\0\2\123\63\0\2\124\64\0\1\125"+
    "\63\0\2\25\4\0\2\25\1\0\14\25\1\126\12\25"+
    "\25\0\2\25\4\0\2\25\1\0\16\25\1\127\10\25"+
    "\25\0\2\25\4\0\2\25\1\0\5\25\1\130\21\25"+
    "\25\0\2\25\4\0\2\25\1\0\22\25\1\131\4\25"+
    "\25\0\2\25\4\0\2\25\1\0\1\25\1\132\25\25"+
    "\25\0\2\25\4\0\2\25\1\0\15\25\1\133\11\25"+
    "\25\0\2\25\4\0\2\25\1\0\24\25\1\134\2\25"+
    "\25\0\2\25\4\0\2\25\1\0\6\25\1\135\20\25"+
    "\25\0\2\25\4\0\2\25\1\0\22\25\1\136\4\25"+
    "\25\0\2\25\4\0\2\25\1\0\17\25\1\137\7\25"+
    "\25\0\2\25\4\0\2\25\1\0\24\25\1\140\2\25"+
    "\25\0\2\25\4\0\2\25\1\0\13\25\1\141\13\25"+
    "\25\0\2\25\4\0\2\25\1\0\16\25\1\142\10\25"+
    "\25\0\2\25\4\0\2\25\1\0\5\25\1\143\21\25"+
    "\25\0\2\25\4\0\2\25\1\0\23\25\1\144\3\25"+
    "\25\0\2\25\4\0\2\25\1\0\22\25\1\145\4\25"+
    "\25\0\2\25\4\0\2\25\1\0\5\25\1\146\21\25"+
    "\25\0\2\25\4\0\2\25\1\0\23\25\1\147\3\25"+
    "\25\0\2\25\4\0\2\25\1\0\21\25\1\150\5\25"+
    "\25\0\2\25\4\0\2\25\1\0\11\25\1\151\15\25"+
    "\25\0\2\25\4\0\2\25\1\0\24\25\1\152\2\25"+
    "\25\0\2\25\4\0\2\25\1\0\11\25\1\153\15\25"+
    "\5\0\15\116\1\154\47\116\2\121\1\3\1\4\61\121"+
    "\20\0\2\125\63\0\2\25\4\0\2\25\1\0\1\25"+
    "\1\155\25\25\25\0\2\25\4\0\2\25\1\0\13\25"+
    "\1\156\13\25\25\0\2\25\4\0\2\25\1\0\1\25"+
    "\1\157\25\25\25\0\2\25\4\0\2\25\1\0\5\25"+
    "\1\160\21\25\25\0\2\25\4\0\2\25\1\0\21\25"+
    "\1\161\5\25\25\0\2\25\4\0\2\25\1\0\23\25"+
    "\1\162\3\25\25\0\2\25\4\0\2\25\1\0\1\25"+
    "\1\163\25\25\25\0\2\25\4\0\2\25\1\0\5\25"+
    "\1\164\21\25\25\0\2\25\4\0\2\25\1\0\23\25"+
    "\1\165\3\25\25\0\2\25\4\0\2\25\1\0\1\25"+
    "\1\166\25\25\25\0\2\25\4\0\2\25\1\0\22\25"+
    "\1\167\4\25\25\0\2\25\4\0\2\25\1\0\1\25"+
    "\1\170\25\25\25\0\2\25\4\0\2\25\1\0\1\25"+
    "\1\171\25\25\25\0\2\25\4\0\2\25\1\0\22\25"+
    "\1\172\4\25\25\0\2\25\4\0\2\25\1\0\20\25"+
    "\1\173\6\25\25\0\2\25\4\0\2\25\1\0\24\25"+
    "\1\174\2\25\25\0\2\25\4\0\2\25\1\0\11\25"+
    "\1\175\15\25\25\0\2\25\4\0\2\25\1\0\23\25"+
    "\1\176\3\25\25\0\2\25\4\0\2\25\1\0\5\25"+
    "\1\177\21\25\25\0\2\25\4\0\2\25\1\0\13\25"+
    "\1\200\13\25\5\0\15\116\1\154\44\116\1\3\2\116"+
    "\20\0\2\25\4\0\2\25\1\0\11\25\1\201\15\25"+
    "\25\0\2\25\4\0\2\25\1\0\12\25\1\202\14\25"+
    "\25\0\2\25\4\0\2\25\1\0\24\25\1\203\2\25"+
    "\25\0\2\25\4\0\2\25\1\0\26\25\1\204\25\0"+
    "\2\25\4\0\2\25\1\0\13\25\1\205\13\25\25\0"+
    "\2\25\4\0\2\25\1\0\5\25\1\206\21\25\25\0"+
    "\2\25\4\0\2\25\1\0\23\25\1\207\3\25\25\0"+
    "\2\25\4\0\2\25\1\0\23\25\1\210\3\25\25\0"+
    "\2\25\4\0\2\25\1\0\1\211\26\25\25\0\2\25"+
    "\4\0\2\25\1\0\24\25\1\212\2\25\25\0\2\25"+
    "\4\0\2\25\1\0\21\25\1\213\5\25\25\0\2\25"+
    "\4\0\2\25\1\0\15\25\1\214\11\25\25\0\2\25"+
    "\4\0\2\25\1\0\3\25\1\215\23\25\25\0\2\25"+
    "\4\0\2\25\1\0\5\25\1\216\21\25\25\0\2\25"+
    "\4\0\2\25\1\0\15\25\1\217\11\25\25\0\2\25"+
    "\4\0\2\25\1\0\13\25\1\220\13\25\25\0\2\25"+
    "\4\0\2\25\1\0\5\25\1\221\2\25\1\222\16\25"+
    "\25\0\2\25\4\0\2\25\1\0\23\25\1\223\3\25"+
    "\25\0\2\25\4\0\2\25\1\0\1\25\1\224\25\25"+
    "\25\0\2\25\4\0\2\25\1\0\15\25\1\225\11\25"+
    "\25\0\2\25\4\0\2\25\1\0\7\25\1\226\17\25"+
    "\25\0\2\25\4\0\2\25\1\0\10\25\1\227\16\25"+
    "\25\0\2\25\4\0\2\25\1\0\1\230\26\25\25\0"+
    "\2\25\4\0\2\25\1\0\23\25\1\231\3\25\25\0"+
    "\2\25\4\0\2\25\1\0\21\25\1\232\5\25\25\0"+
    "\2\25\4\0\2\25\1\0\5\25\1\233\21\25\25\0"+
    "\2\25\4\0\2\25\1\0\5\25\1\234\21\25\25\0"+
    "\2\25\4\0\2\25\1\0\13\25\1\235\13\25\25\0"+
    "\2\25\4\0\2\25\1\0\1\236\26\25\25\0\2\25"+
    "\4\0\2\25\1\0\1\237\26\25\25\0\2\25\4\0"+
    "\2\25\1\0\21\25\1\240\5\25\25\0\2\25\4\0"+
    "\2\25\1\0\23\25\1\241\3\25\25\0\2\25\4\0"+
    "\2\25\1\0\1\242\26\25\25\0\2\25\4\0\2\25"+
    "\1\0\5\25\1\243\21\25\25\0\2\25\4\0\2\25"+
    "\1\0\23\25\1\244\3\25\25\0\2\25\4\0\2\25"+
    "\1\0\5\25\1\245\21\25\5\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6095];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\1\1\3\11\1\1\1\11"+
    "\1\1\1\11\1\1\1\11\4\1\1\11\1\1\1\11"+
    "\20\1\1\11\1\1\1\0\1\11\1\0\2\11\3\0"+
    "\5\11\30\1\1\0\2\11\1\1\1\11\31\1\1\0"+
    "\71\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    // ===== ESCRITURA DE TOKENS A ARCHIVO =====
    private static PrintWriter tokenWriter = null;
    private static PrintWriter errorWriter = null;

    public static void initTokenWriter(String filename) throws IOException {
        tokenWriter = new PrintWriter(new FileWriter(filename));
        tokenWriter.println("LÍNEA \tCOLUMNA \tTOKEN                \tLEXEMA");
        tokenWriter.println("-----------------------------------------------------------------------");
    }

    public static void initErrorWriter(String filename) throws IOException {
        errorWriter = new PrintWriter(new FileWriter(filename));
        errorWriter.println("TIPO              \tLÍNEA \tCOLUMNA \tLEXEMA");
        errorWriter.println("-----------------------------------------------------------------------");
    }

    public static void closeTokenWriter() {
        if (tokenWriter != null) {
            tokenWriter.close();
            tokenWriter = null;
        }
    }

    public static void closeErrorWriter() {
        if (errorWriter != null) {
            errorWriter.close();
            errorWriter = null;
        }
    }

    /**
     * Llamado desde Parser.cup (syntax_error / unrecovered_syntax_error)
     * para registrar errores sintácticos en el archivo de errores.
     */
    public static void writeError(int line, int column, String lexema) {
        if (errorWriter != null) {
            errorWriter.printf("%-18s\t%-6d\t%-8d\t%s%n",
                "ERROR_SINTÁCTICO", line, column, lexema);
            errorWriter.flush();
        }
    }

    // -----------------------------------------------------------------------
    // Métodos internos del lexer
    // -----------------------------------------------------------------------

    private Symbol symbol(int type) {
        String tokenName = sym.terminalNames[type];
        writeToken(tokenName, yytext());
        return new Symbol(type, yyline + 1, yycolumn + 1);
    }

    // CAMBIO: se agregó llamada a addSymbol para IDs y literales
    private Symbol symbol(int type, Object value) {
        String tokenName = sym.terminalNames[type];
        writeToken(tokenName, yytext());
        if (type == sym.ID        ||
            type == sym.INT_LIT   ||
            type == sym.FLOAT_LIT ||
            type == sym.EXP_LIT   ||
            type == sym.FRAC_LIT  ||
            type == sym.BOOL_LIT  ||
            type == sym.CHAR_LIT  ||
            type == sym.STRING_LIT) {
            addSymbol(yytext(), tokenName,
                value != null ? value.toString() : yytext(),
                yyline + 1, yycolumn + 1);
        }
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }

    private void writeToken(String tokenName, String lexema) {
        if (tokenWriter != null) {
            tokenWriter.printf("%-6d\t%-8d\t%-21s\t%s%n",
                yyline + 1, yycolumn + 1, tokenName, lexema);
            tokenWriter.flush();
        }
    }

    // ===== TABLA DE SÍMBOLOS =====
    private static java.util.LinkedHashMap<String, String[]> symbolTable =
        new java.util.LinkedHashMap<>();
    private static PrintWriter symbolWriter = null;

    public static void initSymbolWriter(String filename) throws IOException {
        symbolWriter = new PrintWriter(new FileWriter(filename));
        symbolWriter.println("NOMBRE            \tTIPO              \tVALOR             \tLÍNEA \tCOLUMNA");
        symbolWriter.println("-------------------------------------------------------------------------------");
    }

    public static void closeSymbolWriter() {
        if (symbolWriter != null) {
            symbolWriter.close();
            symbolWriter = null;
        }
    }

    public static void addSymbol(String name, String tipo, String valor, int line, int col) {
        if (!symbolTable.containsKey(name)) {
            symbolTable.put(name, new String[]{tipo, valor, String.valueOf(line), String.valueOf(col)});
            if (symbolWriter != null) {
                symbolWriter.printf("%-18s\t%-18s\t%-18s\t%-6s\t%s%n", name, tipo, valor, line, col);
                symbolWriter.flush();
            }
        }
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { String lex = yytext();
                            int lin = yyline + 1, col = yycolumn + 1;
                            String msg = "Error léxico en línea " + lin +
                                         ", columna " + col +
                                         ": carácter no reconocido '" + lex + "'";
                            System.err.println(msg);
                            // Registrar en el archivo de tokens
                            if (tokenWriter != null) {
                                tokenWriter.printf("%-6d\t%-8d\t%-21s\t%s%n",
                                    lin, col, "ERROR_LÉXICO", lex);
                                tokenWriter.flush();
                            }
                            // Registrar en el archivo de errores
                            if (errorWriter != null) {
                                errorWriter.printf("%-18s\t%-6d\t%-8d\t%s%n",
                                    "ERROR_LÉXICO", lin, col, lex);
                                errorWriter.flush();
                            }
                            // CRÍTICO: retornar sym.error para que CUP no se bloquee
                            return new Symbol(sym.error, lin, col, lex);
            }
          // fall through
          case 60: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 61: break;
          case 3:
            { return symbol(sym.EXCLAMATION);
            }
          // fall through
          case 62: break;
          case 4:
            { return symbol(sym.OR);
            }
          // fall through
          case 63: break;
          case 5:
            { return symbol(sym.NOT);
            }
          // fall through
          case 64: break;
          case 6:
            { return symbol(sym.MOD);
            }
          // fall through
          case 65: break;
          case 7:
            { return symbol(sym.TIMES);
            }
          // fall through
          case 66: break;
          case 8:
            { return symbol(sym.PLUS);
            }
          // fall through
          case 67: break;
          case 9:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 68: break;
          case 10:
            { return symbol(sym.MINUS);
            }
          // fall through
          case 69: break;
          case 11:
            { return symbol(sym.DIVIDE);
            }
          // fall through
          case 70: break;
          case 12:
            { return symbol(sym.INT_LIT, Integer.parseInt(yytext()));
            }
          // fall through
          case 71: break;
          case 13:
            { return symbol(sym.COLON);
            }
          // fall through
          case 72: break;
          case 14:
            { return symbol(sym.AND);
            }
          // fall through
          case 73: break;
          case 15:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 74: break;
          case 16:
            { return symbol(sym.POWER);
            }
          // fall through
          case 75: break;
          case 17:
            { return symbol(sym.TILDE);
            }
          // fall through
          case 76: break;
          case 18:
            { String str = yytext();
                            return symbol(sym.STRING_LIT, str.substring(1, str.length() - 1));
            }
          // fall through
          case 77: break;
          case 19:
            { return symbol(sym.INCREMENT);
            }
          // fall through
          case 78: break;
          case 20:
            { return symbol(sym.DECREMENT);
            }
          // fall through
          case 79: break;
          case 21:
            { return symbol(sym.RBLOCK);
            }
          // fall through
          case 80: break;
          case 22:
            { return symbol(sym.ASSIGN);
            }
          // fall through
          case 81: break;
          case 23:
            { return symbol(sym.LBRACKET);
            }
          // fall through
          case 82: break;
          case 24:
            { return symbol(sym.LPAR);
            }
          // fall through
          case 83: break;
          case 25:
            { return symbol(sym.RBRACKET);
            }
          // fall through
          case 84: break;
          case 26:
            { return symbol(sym.DO);
            }
          // fall through
          case 85: break;
          case 27:
            { return symbol(sym.IF);
            }
          // fall through
          case 86: break;
          case 28:
            { return symbol(sym.LBLOCK);
            }
          // fall through
          case 87: break;
          case 29:
            { return symbol(sym.RPAR);
            }
          // fall through
          case 88: break;
          case 30:
            { return symbol(sym.CHAR_LIT, yytext().charAt(1));
            }
          // fall through
          case 89: break;
          case 31:
            { return symbol(sym.FLOAT_LIT, Float.parseFloat(yytext()));
            }
          // fall through
          case 90: break;
          case 32:
            { return symbol(sym.FRAC_LIT, yytext());
            }
          // fall through
          case 91: break;
          case 33:
            { return symbol(sym.EXP_LIT, yytext());
            }
          // fall through
          case 92: break;
          case 34:
            { return symbol(sym.CIN);
            }
          // fall through
          case 93: break;
          case 35:
            { return symbol(sym.INT);
            }
          // fall through
          case 94: break;
          case 36:
            { return symbol(sym.BOOL);
            }
          // fall through
          case 95: break;
          case 37:
            { return symbol(sym.CASE);
            }
          // fall through
          case 96: break;
          case 38:
            { return symbol(sym.CHAR);
            }
          // fall through
          case 97: break;
          case 39:
            { return symbol(sym.COUT);
            }
          // fall through
          case 98: break;
          case 40:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 99: break;
          case 41:
            { return symbol(sym.BOOL_LIT, Boolean.valueOf(true));
            }
          // fall through
          case 100: break;
          case 42:
            { return symbol(sym.BREAK);
            }
          // fall through
          case 101: break;
          case 43:
            { return symbol(sym.EMPTY);
            }
          // fall through
          case 102: break;
          case 44:
            { return symbol(sym.EQUAL);
            }
          // fall through
          case 103: break;
          case 45:
            { return symbol(sym.BOOL_LIT, Boolean.valueOf(false));
            }
          // fall through
          case 104: break;
          case 46:
            { return symbol(sym.FLOAT);
            }
          // fall through
          case 105: break;
          case 47:
            { return symbol(sym.WHILE);
            }
          // fall through
          case 106: break;
          case 48:
            { return symbol(sym.LESS_T);
            }
          // fall through
          case 107: break;
          case 49:
            { return symbol(sym.RETURN);
            }
          // fall through
          case 108: break;
          case 50:
            { return symbol(sym.STRING);
            }
          // fall through
          case 109: break;
          case 51:
            { return symbol(sym.SWITCH);
            }
          // fall through
          case 110: break;
          case 52:
            { return symbol(sym.DEFAULT);
            }
          // fall through
          case 111: break;
          case 53:
            { return symbol(sym.LESS_TE);
            }
          // fall through
          case 112: break;
          case 54:
            { return symbol(sym.N_EQUAL);
            }
          // fall through
          case 113: break;
          case 55:
            { return symbol(sym.MAIN);
            }
          // fall through
          case 114: break;
          case 56:
            { return symbol(sym.GREATER_T);
            }
          // fall through
          case 115: break;
          case 57:
            { return symbol(sym.GREATER_TE);
            }
          // fall through
          case 116: break;
          case 58:
            { return symbol(sym.GREATHER_T);
            }
          // fall through
          case 117: break;
          case 59:
            { return symbol(sym.GREATHER_TE);
            }
          // fall through
          case 118: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
