
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOAT_LIT = 51;
  public static final int LESS_TE = 23;
  public static final int CHAR_LIT = 55;
  public static final int DIVIDE = 42;
  public static final int LBRACKET = 32;
  public static final int INCREMENT = 45;
  public static final int POWER = 44;
  public static final int CHAR = 5;
  public static final int EMPTY = 2;
  public static final int CASE = 13;
  public static final int EXP_LIT = 52;
  public static final int INT = 3;
  public static final int GREATER_TE = 25;
  public static final int DECREMENT = 46;
  public static final int MINUS = 40;
  public static final int TILDE = 35;
  public static final int NOT = 49;
  public static final int AND = 47;
  public static final int RPAR = 29;
  public static final int GREATER_T = 24;
  public static final int OR = 48;
  public static final int COMMA = 37;
  public static final int BOOL = 6;
  public static final int FRAC_LIT = 53;
  public static final int PLUS = 39;
  public static final int EXCLAMATION = 36;
  public static final int ASSIGN = 34;
  public static final int MAIN = 19;
  public static final int IF = 8;
  public static final int ID = 57;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int RBRACKET = 33;
  public static final int EQUAL = 20;
  public static final int GREATHER_TE = 27;
  public static final int error = 1;
  public static final int LBLOCK = 30;
  public static final int MOD = 43;
  public static final int CIN = 17;
  public static final int BREAK = 16;
  public static final int SWITCH = 12;
  public static final int RBLOCK = 31;
  public static final int TIMES = 41;
  public static final int COLON = 38;
  public static final int ELSE = 9;
  public static final int COUT = 18;
  public static final int N_EQUAL = 21;
  public static final int WHILE = 11;
  public static final int DEFAULT = 14;
  public static final int FLOAT = 4;
  public static final int BOOL_LIT = 54;
  public static final int GREATHER_T = 26;
  public static final int LPAR = 28;
  public static final int STRING = 7;
  public static final int LESS_T = 22;
  public static final int STRING_LIT = 56;
  public static final int INT_LIT = 50;
  public static final int DO = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "EMPTY",
  "INT",
  "FLOAT",
  "CHAR",
  "BOOL",
  "STRING",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "RETURN",
  "BREAK",
  "CIN",
  "COUT",
  "MAIN",
  "EQUAL",
  "N_EQUAL",
  "LESS_T",
  "LESS_TE",
  "GREATER_T",
  "GREATER_TE",
  "GREATHER_T",
  "GREATHER_TE",
  "LPAR",
  "RPAR",
  "LBLOCK",
  "RBLOCK",
  "LBRACKET",
  "RBRACKET",
  "ASSIGN",
  "TILDE",
  "EXCLAMATION",
  "COMMA",
  "COLON",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "POWER",
  "INCREMENT",
  "DECREMENT",
  "AND",
  "OR",
  "NOT",
  "INT_LIT",
  "FLOAT_LIT",
  "EXP_LIT",
  "FRAC_LIT",
  "BOOL_LIT",
  "CHAR_LIT",
  "STRING_LIT",
  "ID"
  };
}

